# Generated by Django 6.0.5 on 2026-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_profile_location_profile_phone_profile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default=True, upload_to='profile_images/'),
        ),
    ]
