# Generated by Django 6.0.5 on 2026-09-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_address_address_type_address_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_at',
        ),
    ]
