# Generated by Django 6.0.5 on 2026-09-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_user_product_wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
